/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AnamneseRouteImport } from './routes/anamnese'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaisRouteImport } from './routes/mais'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as AtendimentoNovoRouteImport } from './routes/atendimento.novo'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as ClientesClientIdRouteImport } from './routes/clientes.$clientId'
import { Route as ClientesNovoRouteImport } from './routes/clientes.novo'
import { Route as FichaTokenRouteImport } from './routes/ficha/$token'
import { Route as ServicosNovoRouteImport } from './routes/servicos_.novo'
import { Route as AnamneseVisualizarIdRouteImport } from './routes/anamnese/visualizar.$id'
import { Route as ClientesClientIdIndexRouteImport } from './routes/clientes.$clientId.index'
import { Route as ClientesClientIdEditarRouteImport } from './routes/clientes.$clientId.editar'
import { Route as ServicosServiceIdEditarRouteImport } from './routes/servicos_.$serviceId.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AnamneseRoute = AnamneseRouteImport.update({
  id: '/anamnese',
  path: '/anamnese',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisRoute = MaisRouteImport.update({
  id: '/mais',
  path: '/mais',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoNovoRoute = AtendimentoNovoRouteImport.update({
  id: '/atendimento/novo',
  path: '/atendimento/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesClientIdRoute = ClientesClientIdRouteImport.update({
  id: '/clientes/$clientId',
  path: '/clientes/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesNovoRoute = ClientesNovoRouteImport.update({
  id: '/clientes/novo',
  path: '/clientes/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const FichaTokenRoute = FichaTokenRouteImport.update({
  id: '/ficha/$token',
  path: '/ficha/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosNovoRoute = ServicosNovoRouteImport.update({
  id: '/servicos_/novo',
  path: '/servicos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const AnamneseVisualizarIdRoute = AnamneseVisualizarIdRouteImport.update({
  id: '/visualizar/$id',
  path: '/visualizar/$id',
  getParentRoute: () => AnamneseRoute,
} as any)
const ClientesClientIdIndexRoute = ClientesClientIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientesClientIdRoute,
} as any)
const ClientesClientIdEditarRoute = ClientesClientIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => ClientesClientIdRoute,
} as any)
const ServicosServiceIdEditarRoute = ServicosServiceIdEditarRouteImport.update({
  id: '/servicos_/$serviceId/editar',
  path: '/servicos/$serviceId/editar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/anamnese': typeof AnamneseRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/login': typeof LoginRoute
  '/mais': typeof MaisRoute
  '/notificacoes': typeof NotificacoesRoute
  '/perfil': typeof PerfilRoute
  '/servicos': typeof ServicosRoute
  '/atendimento/novo': typeof AtendimentoNovoRoute
  '/clientes/$clientId': typeof ClientesClientIdRouteWithChildren
  '/clientes/novo': typeof ClientesNovoRoute
  '/ficha/$token': typeof FichaTokenRoute
  '/servicos/novo': typeof ServicosNovoRoute
  '/clientes/': typeof ClientesIndexRoute
  '/anamnese/visualizar/$id': typeof AnamneseVisualizarIdRoute
  '/clientes/$clientId/editar': typeof ClientesClientIdEditarRoute
  '/servicos/$serviceId/editar': typeof ServicosServiceIdEditarRoute
  '/clientes/$clientId/': typeof ClientesClientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/anamnese': typeof AnamneseRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/login': typeof LoginRoute
  '/mais': typeof MaisRoute
  '/notificacoes': typeof NotificacoesRoute
  '/perfil': typeof PerfilRoute
  '/servicos': typeof ServicosRoute
  '/atendimento/novo': typeof AtendimentoNovoRoute
  '/clientes/novo': typeof ClientesNovoRoute
  '/ficha/$token': typeof FichaTokenRoute
  '/servicos/novo': typeof ServicosNovoRoute
  '/clientes': typeof ClientesIndexRoute
  '/anamnese/visualizar/$id': typeof AnamneseVisualizarIdRoute
  '/clientes/$clientId/editar': typeof ClientesClientIdEditarRoute
  '/servicos/$serviceId/editar': typeof ServicosServiceIdEditarRoute
  '/clientes/$clientId': typeof ClientesClientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/anamnese': typeof AnamneseRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/login': typeof LoginRoute
  '/mais': typeof MaisRoute
  '/notificacoes': typeof NotificacoesRoute
  '/perfil': typeof PerfilRoute
  '/servicos': typeof ServicosRoute
  '/atendimento/novo': typeof AtendimentoNovoRoute
  '/clientes/$clientId': typeof ClientesClientIdRouteWithChildren
  '/clientes/novo': typeof ClientesNovoRoute
  '/ficha/$token': typeof FichaTokenRoute
  '/servicos_/novo': typeof ServicosNovoRoute
  '/clientes/': typeof ClientesIndexRoute
  '/anamnese/visualizar/$id': typeof AnamneseVisualizarIdRoute
  '/clientes/$clientId/editar': typeof ClientesClientIdEditarRoute
  '/servicos_/$serviceId/editar': typeof ServicosServiceIdEditarRoute
  '/clientes/$clientId/': typeof ClientesClientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/anamnese'
    | '/cadastro'
    | '/configuracoes'
    | '/login'
    | '/mais'
    | '/notificacoes'
    | '/perfil'
    | '/servicos'
    | '/atendimento/novo'
    | '/clientes/$clientId'
    | '/clientes/novo'
    | '/ficha/$token'
    | '/servicos/novo'
    | '/clientes/'
    | '/anamnese/visualizar/$id'
    | '/clientes/$clientId/editar'
    | '/servicos/$serviceId/editar'
    | '/clientes/$clientId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/anamnese'
    | '/cadastro'
    | '/configuracoes'
    | '/login'
    | '/mais'
    | '/notificacoes'
    | '/perfil'
    | '/servicos'
    | '/atendimento/novo'
    | '/clientes/novo'
    | '/ficha/$token'
    | '/servicos/novo'
    | '/clientes'
    | '/anamnese/visualizar/$id'
    | '/clientes/$clientId/editar'
    | '/servicos/$serviceId/editar'
    | '/clientes/$clientId'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/anamnese'
    | '/cadastro'
    | '/configuracoes'
    | '/login'
    | '/mais'
    | '/notificacoes'
    | '/perfil'
    | '/servicos'
    | '/atendimento/novo'
    | '/clientes/$clientId'
    | '/clientes/novo'
    | '/ficha/$token'
    | '/servicos_/novo'
    | '/clientes/'
    | '/anamnese/visualizar/$id'
    | '/clientes/$clientId/editar'
    | '/servicos_/$serviceId/editar'
    | '/clientes/$clientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AnamneseRoute: typeof AnamneseRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  LoginRoute: typeof LoginRoute
  MaisRoute: typeof MaisRoute
  NotificacoesRoute: typeof NotificacoesRoute
  PerfilRoute: typeof PerfilRoute
  ServicosRoute: typeof ServicosRoute
  AtendimentoNovoRoute: typeof AtendimentoNovoRoute
  ClientesClientIdRoute: typeof ClientesClientIdRouteWithChildren
  ClientesNovoRoute: typeof ClientesNovoRoute
  FichaTokenRoute: typeof FichaTokenRoute
  ServicosNovoRoute: typeof ServicosNovoRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  ServicosServiceIdEditarRoute: typeof ServicosServiceIdEditarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anamnese': {
      id: '/anamnese'
      path: '/anamnese'
      fullPath: '/anamnese'
      preLoaderRoute: typeof AnamneseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mais': {
      id: '/mais'
      path: '/mais'
      fullPath: '/mais'
      preLoaderRoute: typeof MaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento/novo': {
      id: '/atendimento/novo'
      path: '/atendimento/novo'
      fullPath: '/atendimento/novo'
      preLoaderRoute: typeof AtendimentoNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$clientId': {
      id: '/clientes/$clientId'
      path: '/clientes/$clientId'
      fullPath: '/clientes/$clientId'
      preLoaderRoute: typeof ClientesClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/novo': {
      id: '/clientes/novo'
      path: '/clientes/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof ClientesNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ficha/$token': {
      id: '/ficha/$token'
      path: '/ficha/$token'
      fullPath: '/ficha/$token'
      preLoaderRoute: typeof FichaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos_/novo': {
      id: '/servicos_/novo'
      path: '/servicos/novo'
      fullPath: '/servicos/novo'
      preLoaderRoute: typeof ServicosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anamnese/visualizar/$id': {
      id: '/anamnese/visualizar/$id'
      path: '/visualizar/$id'
      fullPath: '/anamnese/visualizar/$id'
      preLoaderRoute: typeof AnamneseVisualizarIdRouteImport
      parentRoute: typeof AnamneseRoute
    }
    '/clientes/$clientId/': {
      id: '/clientes/$clientId/'
      path: '/'
      fullPath: '/clientes/$clientId/'
      preLoaderRoute: typeof ClientesClientIdIndexRouteImport
      parentRoute: typeof ClientesClientIdRoute
    }
    '/clientes/$clientId/editar': {
      id: '/clientes/$clientId/editar'
      path: '/editar'
      fullPath: '/clientes/$clientId/editar'
      preLoaderRoute: typeof ClientesClientIdEditarRouteImport
      parentRoute: typeof ClientesClientIdRoute
    }
    '/servicos_/$serviceId/editar': {
      id: '/servicos_/$serviceId/editar'
      path: '/servicos/$serviceId/editar'
      fullPath: '/servicos/$serviceId/editar'
      preLoaderRoute: typeof ServicosServiceIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AnamneseRouteChildren {
  AnamneseVisualizarIdRoute: typeof AnamneseVisualizarIdRoute
}

const AnamneseRouteChildren: AnamneseRouteChildren = {
  AnamneseVisualizarIdRoute: AnamneseVisualizarIdRoute,
}

const AnamneseRouteWithChildren = AnamneseRoute._addFileChildren(
  AnamneseRouteChildren,
)

interface ClientesClientIdRouteChildren {
  ClientesClientIdEditarRoute: typeof ClientesClientIdEditarRoute
  ClientesClientIdIndexRoute: typeof ClientesClientIdIndexRoute
}

const ClientesClientIdRouteChildren: ClientesClientIdRouteChildren = {
  ClientesClientIdEditarRoute: ClientesClientIdEditarRoute,
  ClientesClientIdIndexRoute: ClientesClientIdIndexRoute,
}

const ClientesClientIdRouteWithChildren =
  ClientesClientIdRoute._addFileChildren(ClientesClientIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AnamneseRoute: AnamneseRouteWithChildren,
  CadastroRoute: CadastroRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  LoginRoute: LoginRoute,
  MaisRoute: MaisRoute,
  NotificacoesRoute: NotificacoesRoute,
  PerfilRoute: PerfilRoute,
  ServicosRoute: ServicosRoute,
  AtendimentoNovoRoute: AtendimentoNovoRoute,
  ClientesClientIdRoute: ClientesClientIdRouteWithChildren,
  ClientesNovoRoute: ClientesNovoRoute,
  FichaTokenRoute: FichaTokenRoute,
  ServicosNovoRoute: ServicosNovoRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  ServicosServiceIdEditarRoute: ServicosServiceIdEditarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
